name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
            
      - name: Check Node Version
        run: node --version
          
      - name: Check Yarn Version
        run: yarn --version
          
      - name: Install Dependencies
        run: yarn install
          
      - name: Start Build
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-actions@4.1.3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./build
