name: Deploy Firebase App

on:
  push:
    branches:
      - firebase

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
      REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
      REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
      REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
      REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
            
      - name: Check Node Version
        run: node --version
          
      - name: Check Yarn Version
        run: yarn --version
          
      - name: Install Dependencies
        run: yarn install

      - name: Start Build
        run: yarn build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PERSONAL_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages